"""P11-T5: the living block-event-v1 activity-ledger row.

Laws pinned here (the byte-parity replay itself lives in
tools/shield_vectors_check.py + xr-core/shield/tests/test_golden_vectors.cc):

  * the golden row is generated by the C++ core and byte-identical from
    BOTH backends (compiled host + fakes/shield.py);
  * tools/xr_schema.py validates the golden AND the live emitter outputs,
    and the schema is STRICT (extra keys, non-frozen action spellings,
    out-of-vocabulary why_codes, wrong types all fail);
  * the five-way why_code sync: reason-codes.json == reason-codes.md ==
    schema enum == host_protocol.md closed set == the vectors' usage
    (every code appears, no code outside the table does);
  * doc/code match (the P8 attention-budget pattern): the ring cap (256)
    and view budget (64 KiB) constants in xr-core events.h are mirrored
    by the contract doc, and the 90-day/never-uploaded retention law is
    stated where P13 will enforce it.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[3]
CORE = REPO.parent / "xr-core"
FAKE = CORE / "fakes" / "shield.py"
HOST = CORE / "shield" / "tests" / "build" / "shield_host"
GOLDEN_PATH = REPO / "docs" / "contracts" / "tests" / "golden-block-event.json"
CONTRACT_MD = REPO / "docs" / "contracts" / "block-event-v1.md"
CODES_JSON = REPO / "docs" / "shield" / "reason-codes.json"
CODES_MD = REPO / "docs" / "shield" / "reason-codes.md"
EVENTS_H = CORE / "shield" / "core" / "events.h"
PROTOCOL_MD = CORE / "shield" / "host_protocol.md"
VECTORS = REPO / "docs" / "contracts" / "vectors" / "shield-v1.json"

sys.path.insert(0, str(REPO / "tools"))
import xr_schema  # noqa: E402
from shield_vector_families_t5 import GOLDEN_ARGS  # noqa: E402

HOST_SKIP = ("tool absent: compiled xr-core shield_host "
             "(cd xr-core && make -C shield/tests build) — needed for: "
             "golden byte parity from the compiled backend")


def canonical(obj) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"))


def frame(args: dict) -> str:
    return canonical({"args": args, "method": "event-emit"})


def run_backend(cmd: list[str], args: dict) -> tuple[str, int]:
    r = subprocess.run(cmd, input=frame(args), capture_output=True,
                       text=True, timeout=60)
    return r.stdout.strip(), r.returncode


def golden() -> dict:
    return json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))


def schema() -> dict:
    path = REPO / xr_schema.SCHEMA_DIR / xr_schema.SCHEMAS["block-event"]
    return json.loads(path.read_text(encoding="utf-8"))


def validate(doc) -> list[str]:
    errs: list[str] = []
    xr_schema._validate(doc, schema(), "", errs)
    return errs


def protocol_why_codes() -> list[str]:
    text = PROTOCOL_MD.read_text(encoding="utf-8")
    m = re.search(r"`verdict\.why_code`:(.*?)(?=\n- )", text, re.S)
    assert m, "host_protocol.md lost its verdict.why_code bullet"
    return re.findall(r"`([a-z0-9][a-z0-9-]*)`", m.group(1))


def vector_emit_cases() -> list[dict]:
    doc = json.loads(VECTORS.read_text(encoding="utf-8"))
    return [c for c in doc["cases"] if c.get("method") == "event-emit"]


# ---------------------------------------------------------- golden bytes


def test_golden_file_self_consistent():
    text = GOLDEN_PATH.read_text(encoding="utf-8")
    assert text == canonical(golden()) + "\n"


def test_fake_emits_golden_bytes():
    out, rc = run_backend([sys.executable, str(FAKE)], GOLDEN_ARGS)
    assert rc == 0, out
    assert out == canonical({"row": golden()})


@pytest.mark.skipif(not HOST.exists(), reason=HOST_SKIP)
def test_host_emits_golden_bytes_identical_to_fake():
    h_out, h_rc = run_backend([str(HOST)], GOLDEN_ARGS)
    f_out, f_rc = run_backend([sys.executable, str(FAKE)], GOLDEN_ARGS)
    assert h_rc == f_rc == 0
    assert h_out == f_out == canonical({"row": golden()})


def test_golden_redaction_is_structural():
    row = golden()
    assert row["target"] == "https://tracker.example/ad.js"
    assert "utm_source" not in canonical(row)
    assert "newsletter" not in canonical(row)


# ---------------------------------------------------------- schema laws


def test_schema_validates_golden_and_live_output():
    assert validate(golden()) == []
    out, rc = run_backend([sys.executable, str(FAKE)], GOLDEN_ARGS)
    assert rc == 0
    assert validate(json.loads(out)["row"]) == []


@pytest.mark.parametrize("mutate", [
    pytest.param(lambda r: r.update(extra=1), id="extra-key"),
    pytest.param(lambda r: r.update(action="blocked"), id="non-frozen-action"),
    pytest.param(lambda r: r.update(why_code="because"), id="bad-why"),
    pytest.param(lambda r: r.update(seq="41"), id="seq-not-int"),
    pytest.param(lambda r: r.pop("why_code"), id="missing-required"),
    pytest.param(lambda r: r["origin"].update(port=443), id="origin-extra"),
    pytest.param(lambda r: r["origin"].update(scheme="ftp"), id="bad-scheme"),
    pytest.param(lambda r: r.update(event="block_events"), id="bad-event"),
    pytest.param(lambda r: r.update(contract_version=2), id="bad-version"),
])
def test_schema_is_strict(mutate):
    row = golden()
    mutate(row)
    assert validate(row) != [], "schema accepted a mutated row"


# --------------------------------------------------- five-way vocab sync


def test_reason_code_five_way_sync():
    table = json.loads(CODES_JSON.read_text(encoding="utf-8"))["codes"]
    codes_json = [c["why_code"] for c in table]
    keys = [c["text_key"] for c in table]
    enum = schema()["properties"]["why_code"]["enum"]
    codes_proto = protocol_why_codes()
    md_text = CODES_MD.read_text(encoding="utf-8")

    assert len(codes_json) == len(set(codes_json)) == 11
    assert sorted(codes_json) == sorted(enum) == sorted(codes_proto)
    assert len(keys) == len(set(keys)), "text_keys must be unique"
    assert all(k.startswith("shield.why.") for k in keys)
    actions = set(schema()["properties"]["action"]["enum"])
    assert all(c["default_action"] in actions for c in table)
    for c in table:  # the md mirrors the json (code + key + action present)
        assert f"`{c['why_code']}`" in md_text
        assert f"`{c['text_key']}`" in md_text
        assert f"`{c['default_action']}`" in md_text


def test_vectors_use_exactly_the_table_codes():
    table = json.loads(CODES_JSON.read_text(encoding="utf-8"))["codes"]
    codes = {c["why_code"] for c in table}
    used = set()
    cases = vector_emit_cases()
    assert len(cases) >= 45, "the e-emit family shrank"
    for c in cases:
        row = c["expect"].get("row")
        if row is not None:
            used.add(row["why_code"])
        else:  # every refusal in the family is a typed kMalformedInput
            assert c["expect"].get("error") == "kMalformedInput", c["id"]
            assert c["expect"].get("detail"), c["id"]
    assert used == codes, f"vector why_code drift: {used ^ codes}"


def test_vectors_pin_the_golden_row():
    cases = {c["id"]: c for c in vector_emit_cases()}
    assert "e-emit-golden-instance" in cases
    assert cases["e-emit-golden-instance"]["expect"]["row"] == golden()


# ------------------------------------------------------ doc/code match


def test_ring_cap_doc_code_match():
    header = EVENTS_H.read_text(encoding="utf-8")
    assert "kCapacity = 256" in header
    assert "kChunkBudgetBytes = 65536" in header
    doc = CONTRACT_MD.read_text(encoding="utf-8")
    assert "256" in doc and "64 KiB" in doc


def test_retention_law_stated_where_p13_enforces():
    doc = CONTRACT_MD.read_text(encoding="utf-8")
    codes_md = CODES_MD.read_text(encoding="utf-8")
    for text in (doc, codes_md):
        assert "90-day" in text
        assert "never uploaded" in text
