"""buildsys/gn/gen.py — `./build gen`: resolve argsets and run `gn gen`.

Writes the merged args.gn (via resolve_args) into <checkout>/out/<dir> and runs
`gn gen` from depot_tools/PATH. Zero network by construction (post-sync).
MOCK mode (XR_ALLOW_MOCK=1) prints every line with the MOCK banner and writes
nothing real.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

for _p in [Path(__file__).resolve().parent, *Path(__file__).resolve().parents]:
    if (_p / "_common.py").exists():
        sys.path.insert(0, str(_p))
        break

from _common import ToolError, add_common_flags, emit, main_with_guard, mock_enabled  # noqa: E402
from resolve_args import SELECTABLE, merge_argsets, parse_argset, validate, load_allowlist  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(prog="buildsys/gn/gen.py",
                                     description="Resolve argsets and run gn gen in a synced checkout.")
    parser.add_argument("--checkout", required=True, help="checkout root (contains src/)")
    parser.add_argument("--argset", choices=SELECTABLE, default="xr_release.gn")
    parser.add_argument("--out", default="out/xr_release", help="out dir relative to checkout (default out/xr_release)")
    add_common_flags(parser)
    args = parser.parse_args()

    def run() -> int:
        checkout = Path(args.checkout).resolve()
        if not (checkout / "src" / ".git").exists() and not mock_enabled():
            raise ToolError(f"{checkout} does not look like a synced checkout (src/.git missing); run ./build sync first")

        here = Path(__file__).resolve().parent
        common = parse_argset(here / "argsets" / "xr_common.gni")
        over = parse_argset(here / "argsets" / args.argset)
        merged, overrides = merge_argsets(common, over)
        allow = load_allowlist(here / "argsets")
        failures = validate(merged, allow)
        if failures:
            return emit(args.json, {"tool": "gen", "argset": args.argset}, failures=failures)

        out_dir = checkout / args.out
        if mock_enabled():
            print(f"MOCK MODE — not a build: would write args.gn and run gn gen {out_dir}")
            return emit(args.json, {"tool": "gen", "mode": "mock", "argset": args.argset,
                                    "out": str(out_dir), "flags": merged})
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "args.gn").write_text(
            "# args.gn for XR build (generated by ./build gen)\n" +
            "".join(f"{k} = {v}\n" for k, v in merged.items()),
            encoding="utf-8",
        )
        from _common import run as run_cmd
        run_cmd(["gn", "gen", str(out_dir)], cwd=checkout / "src")
        return emit(args.json, {"tool": "gen", "argset": args.argset, "out": str(out_dir),
                                "overrides": overrides})

    main_with_guard(run)


if __name__ == "__main__":
    main()
