#!/usr/bin/env python3
"""tools/descriptors_to_docs.py — generate docs/contracts/commands.md (P7).

Renders the command roster (the first-20, Plan P7-T5) as a table of
id / scope / tier / danger / predicate / status. The status column is the
availability verdict under the DEFAULT pinned P6 snapshot (so the single
placeholder — tor.open, predicate tor.engine-ready — is shown as
"disabled (P31, placeholder)", never absent: registered, disabled WITH a
reason). This is the P7 DoD #2 roster table and the "no coming-soon rails"
proof for the help index (view #4).

The roster is read from ../xr-core/commands/core/roster_v1.json and the
verdicts come from the frozen Python reference fake (fakes/commands.py) — the
same code the C++ host is byte-parity-tested against. `--check` enforces the
"generated, no hand drift" law (like policy.md / vectors_to_md.py): it
regenerates and fails on any diff.

Exit: 0 pass · 1 fail · 2 usage.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

EXIT_PASS, EXIT_FAIL, EXIT_USAGE = 0, 1, 2

XR_CORE = Path(__file__).resolve().parents[1].parent / "xr-core"
ROSTER = XR_CORE / "commands" / "core" / "roster_v1.json"
DOCS_OUT = Path(__file__).resolve().parents[1] / "docs/contracts/commands.md"
HEADER = "<!-- GENERATED by tools/descriptors_to_docs.py — do not hand-edit; run the tool. -->\n"


def _load_fake():
    sys.path.insert(0, str(XR_CORE / "fakes"))
    import commands as fake  # noqa: PLC0415
    return fake


def _default_snapshot(fake):
    return fake.PolicyState("").default_snapshot()


def generate(repo: Path) -> str:
    fake = _load_fake()
    roster = ROSTER
    doc = roster.read_text(encoding="utf-8")
    import json
    reg = fake.Registry()
    regerr = reg.from_json(json.loads(doc))
    if regerr:
        raise SystemExit(f"roster invalid: {regerr}")
    snap = _default_snapshot(fake)
    lines = [
        HEADER,
        "# Command registry (v1) — the first 20 (Plan P7-T5)",
        "",
        "One registry, four views (palette, menus, shortcut editor, help index +",
        "printable cheatsheet). Placeholders ship **registered and disabled via",
        "availability predicate with a reason** — never absent, never a \"coming",
        "soon\" rail (§10). Tier-1 ≤ 9 controls is enforced in the registry itself",
        "(Plan §1.10 Attention Budget).",
        "",
        f"{len(reg.order)} commands registered; {reg.tier1_count()} in Tier-1 (≤ 9).",
        "",
        "| id | scope | tier | danger | predicate | status |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for c in reg.list():
        available, reason = fake.evaluate(c["predicate_id"], snap)
        status = "enabled" if available else f"disabled ({reason})"
        lines.append(f"| `{c['id']}` | {c['scope']} | {c['attention_tier']} | "
                     f"{c['danger_class']} | `{c['predicate_id']}` | {status} |")
    lines.append("")
    lines.append("Availability predicates read the **pinned** P6 snapshot "
                 "(availability-predicate-contract v1); the UI never calls "
                 "Resolve() live (TOCTOU rule). Dispatch source-tag allowlist, "
                 "id whitelist and danger-confirmation gate live in "
                 "`commands_host` (C++) — see `commands/host_protocol.md`.")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(prog="descriptors_to_docs", description=__doc__)
    p.add_argument("--repo", default=".")
    p.add_argument("--check", action="store_true",
                   help="fail if docs/contracts/commands.md differs from generated")
    p.add_argument("--out", default=str(DOCS_OUT))
    args = p.parse_args(argv)

    out = Path(args.out)
    if not args.check:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(generate(Path(args.repo).resolve()), encoding="utf-8")
        print(f"wrote {out}")
        return EXIT_PASS
    want = generate(Path(args.repo).resolve())
    have = out.read_text(encoding="utf-8") if out.exists() else ""
    if have != want:
        print("FAIL: docs/contracts/commands.md is stale — re-run "
              "`python3 tools/descriptors_to_docs.py` (generated, no hand drift)")
        return EXIT_FAIL
    print(f"PASS: {out} is up to date")
    return EXIT_PASS


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
