#!/usr/bin/env python3
"""tools/gen_server_spec_rs.py — renders the language-neutral server spec
(release/server/spec/*.yaml + the conformance corpus's spec variants) into
release/server/rust/src/spec_generated.rs, the embedded constants the Rust
deployable compiles in. Generated code is committed; --check is diff-clean
(the house pattern).

Exit: 0 written/consistent · 1 drift (--check) · 2 usage. Stdlib only.
"""
from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SPEC = REPO / "release" / "server" / "spec"
OUT = REPO / "release" / "server" / "rust" / "src" / "spec_generated.rs"
CORPUS = REPO / "release" / "server" / "tests" / "conformance.json"

HEADER = """// GENERATED by tools/gen_server_spec_rs.py — DO NOT EDIT.
// Source of truth: release/server/spec/*.yaml + the conformance corpus's
// spec variants. --check is diff-clean law. Every variant blob is the
// COMPLETE merged spec document (canonical JSON) so the Rust deployable
// carries zero YAML/merge logic.
"""


def load_yaml(path: Path) -> dict:
    import yaml  # pinned dev dependency (tools/DEPS.md)
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def merge(dst: dict, src: dict) -> None:
    for k, v in src.items():
        if isinstance(v, dict) and isinstance(dst.get(k), dict):
            merge(dst[k], v)
        else:
            dst[k] = v


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    doc = {name: load_yaml(SPEC / f"{name}.yaml")
           for name in ("channels", "cohorts", "epochs", "version-graph")}
    base = json.dumps(doc, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=True)
    corpus = json.loads(CORPUS.read_text(encoding="utf-8"))
    variants = corpus.get("variants") or {}
    rows: list[tuple[str, str]] = [("base", base)]
    for name in sorted(variants):
        merged = copy.deepcopy(doc)
        for top, sub in variants[name].items():
            merge(merged[top], sub)
        rows.append((name, json.dumps(merged, sort_keys=True,
                                      separators=(",", ":"),
                                      ensure_ascii=True)))
    parts = [HEADER, "pub static SPEC_VARIANTS: &[(&str, &str)] = &["]
    for name, blob in rows:
        parts.append(f'    ("{name}", r##"{blob}"##),')
    parts.append("];\n")
    rendered = "\n".join(parts) + "\n"
    if a.check:
        old = OUT.read_text(encoding="utf-8")
        if old != rendered:
            print(f"FAIL: {OUT} stale (run tools/gen_server_spec_rs.py)")
            return 1
        print(f"PASS: spec_generated.rs diff-clean ({len(rows)} variants)")
        return 0
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} variants)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
