"""tools/identity_card.py — the identity rows of the Isolation Card (P14-CLOSE C-5).

Plan §1.13 says the Isolation Card is "the measured table, data-driven, not
prose". The measured table is the isolation-matrix record
(xr-core/test/isolation/isolation-matrix.json). This module turns that
record into the card's identity rows, one row per matrix mechanism:

  prop      the mechanism id (a token)
  state     holds | violated | not-run | disclosed
  measured  how many identity pairs were executed and PASSED
  pairs     how many identity pairs the matrix declares for the mechanism
  method    a PATH token: where the measurement lives, or how it will run

It writes two outputs from the same rows:
  * xr-core/test/isolation/identity-card-rows.json, which the card's view
    (xr-core/ui/panel/site-tab.ts identityCardView) renders;
  * the generated block in docs/limitations.md between the
    identity-card:begin / identity-card:end markers (§1.13's page).

It is called by tools/isolation_matrix.py, the matrix's own generator, so
the card can never describe a different run than the record. --check there
regenerates both and diffs them byte for byte; nothing is rewritten.

THE CARD REFUSES PROSE. validate_rows() rejects any row whose prop, state
or method is not a token (no spaces, no capitals, nothing a translator would
have to read), any unknown state, any "holds" that was not measured on every
pair, and any "not-run" that claims a measurement. A sentence on the card is
a promise; a token is a pointer to a measurement. The view enforces the same
rules (tests: ui/panel/tests/site-tab.test.mjs; tools/tests/
test_p14c_identity_card.py; negatives: tools/negatives/p14c_c5.sh).

Stdlib only. No wall clock (as_of comes from the caller's --as-of).
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

CONTRACT = "identity-isolation-card-rows"
OUT_CARD = "../xr-core/test/isolation/identity-card-rows.json"
LIMITATIONS = "docs/limitations.md"
BEGIN = ("<!-- identity-card:begin (generated by tools/isolation_matrix.py "
         "from the isolation-matrix record; do not hand-edit) -->")
END = "<!-- identity-card:end -->"
TOKEN_RE = re.compile(r"^[a-z0-9][a-z0-9._:/#-]*$")
STATES = ("holds", "violated", "not-run", "disclosed")
METHOD_MEASURED = "xr-core/test/isolation/isolation-matrix.json"
METHOD_BROWSER = "docs/qa/browser-harness.md"
METHOD_DISCLOSED = "docs/limitations.md#13-exception-ledger-rows"
METHOD_NOT_YET = "xr-core/test/isolation/matrix.yaml"
ROW_KEYS = ("measured", "method", "pairs", "prop", "state")


def build_rows(cells: list[dict[str, Any]],
               matrix: dict[str, Any]) -> list[dict[str, Any]]:
    """One row per mechanism, in matrix order, from the executed cells."""
    rows: list[dict[str, Any]] = []
    for mech in matrix["mechanisms"]:
        mine = [c for c in cells if c["mechanism"] == mech["id"]]
        passed = sum(1 for c in mine if c["verdict"] == "PASS")
        failed = sum(1 for c in mine if c["verdict"] == "FAIL")
        if failed:
            state, method = "violated", METHOD_MEASURED
        elif mine and passed == len(mine):
            state, method = "holds", METHOD_MEASURED
        elif mech["mode"] == "exception":
            state, method = "disclosed", METHOD_DISCLOSED
        elif mech["mode"] == "not-yet":
            state, method = "not-run", METHOD_NOT_YET
        else:
            state, method = "not-run", METHOD_BROWSER
        rows.append({"prop": mech["id"], "state": state,
                     "measured": passed if state != "not-run" else 0,
                     "pairs": len(mine), "method": method})
    return rows


def validate_rows(rows: Any) -> list[str]:
    """Reasons the card refuses these rows (empty list = renderable)."""
    if not isinstance(rows, list) or not rows:
        return ["card: rows must be a non-empty list"]
    bad: list[str] = []
    for i, r in enumerate(rows):
        if not isinstance(r, dict) or tuple(sorted(r)) != ROW_KEYS:
            bad.append(f"card row {i}: keys must be exactly {list(ROW_KEYS)}")
            continue
        for k in ("prop", "state", "method"):
            if not isinstance(r[k], str) or not TOKEN_RE.match(r[k]):
                bad.append(f"card row {i}: {k} is not a token (the card "
                           f"refuses prose): {str(r[k])[:60]!r}")
        if r["state"] not in STATES:
            bad.append(f"card row {i}: state {r['state']!r} not in "
                       f"{list(STATES)}")
        m, n = r["measured"], r["pairs"]
        if not (isinstance(m, int) and isinstance(n, int) and 0 <= m <= n):
            bad.append(f"card row {i}: measured/pairs must be 0 <= m <= n")
            continue
        if r["state"] == "holds" and (n == 0 or m != n):
            bad.append(f"card row {i}: 'holds' needs every pair measured "
                       f"({m}/{n})")
        if r["state"] == "not-run" and m != 0:
            bad.append(f"card row {i}: 'not-run' cannot claim {m} "
                       "measured pair(s)")
    return bad


def card_json(rows: list[dict[str, Any]], as_of: str) -> str:
    doc = {"contract": CONTRACT, "contract_version": 1, "as_of": as_of,
           "generator": "tools/isolation_matrix.py",
           "source": METHOD_MEASURED, "rows": rows}
    return json.dumps(doc, indent=1, sort_keys=True, ensure_ascii=True) + "\n"


def render_block(rows: list[dict[str, Any]]) -> str:
    counts = {s: sum(1 for r in rows if r["state"] == s) for s in STATES}
    lines = [BEGIN, "",
             f"Rows: {len(rows)} mechanisms — " +
             ", ".join(f"{s}={counts[s]}" for s in STATES), "",
             "| mechanism | state | measured / pairs | method |",
             "|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['prop']} | {r['state']} | "
                     f"{r['measured']}/{r['pairs']} | `{r['method']}` |")
    lines += ["", END]
    return "\n".join(lines)


def splice(text: str, block: str) -> str | None:
    """Replace the marked block in text; None when the markers are absent."""
    a, b = text.find(BEGIN), text.find(END)
    if a < 0 or b < a:
        return None
    return text[:a] + block + text[b + len(END):]


def emit(repo: Path, cells: list[dict[str, Any]], matrix: dict[str, Any],
         as_of: str, check: bool, card_path: str = OUT_CARD,
         lim_path: str = LIMITATIONS) -> list[str]:
    """Write (or --check) both card outputs. Returns failure lines."""
    rows = build_rows(cells, matrix)
    fails = validate_rows(rows)
    card = (repo / card_path).resolve()
    lim = (repo / lim_path).resolve()
    new_card = card_json(rows, as_of)
    old_lim = lim.read_text(encoding="utf-8") if lim.exists() else ""
    new_lim = splice(old_lim, render_block(rows))
    if new_lim is None:
        fails.append(f"{LIMITATIONS}: identity-card markers missing")
    if check:
        if card.exists():
            try:
                committed = json.loads(card.read_text(encoding="utf-8"))
                fails += validate_rows(committed.get("rows"))
            except ValueError as exc:
                fails.append(f"{card.name}: not JSON ({exc})")
        if not card.exists() or card.read_text(encoding="utf-8") != new_card:
            fails.append(f"{card.name} drifted from the isolation-matrix "
                         "record — regenerate it")
        if new_lim is not None and new_lim != old_lim:
            fails.append(f"{LIMITATIONS}: the identity-card block drifted "
                         "from the isolation-matrix record — regenerate it")
        return fails
    if not fails:
        card.write_text(new_card, encoding="utf-8")
        if new_lim is not None:
            lim.write_text(new_lim, encoding="utf-8")
    return fails
