"""owners_sync.py — generate/check CODEOWNERS from the S0 path source.

Single source of truth: docs/process/s0-paths.yaml. This tool derives the
CODEOWNERS file for each configured repository and either writes it
(--write) or verifies the committed file matches (--check). CI runs
--check; drift between the S0 source and CODEOWNERS fails the build.

Scope honesty (L5): this tool enforces *path→owner mapping integrity*.
GitHub-side review enforcement (required reviewers on S0 paths) only
exists once the repositories are hosted with branch protection
(human-gated, HG-3); until then this check is the interim control.

Exit codes: 0 = in sync (or written), 1 = drift / error, 2 = usage.
"""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path
from typing import Any

from _common import (
    EXIT_FAIL,
    EXIT_PASS,
    S0_PATHS_FILE,
    ToolError,
    add_common_flags,
    emit,
    load_yaml,
    main_with_usage_guard,
)

HEADER = (
    "# GENERATED by tools/owners_sync.py from docs/process/s0-paths.yaml.\n"
    "# Do not edit by hand — edit the source, then run: python tools/owners_sync.py --write\n"
    "# GitHub-side enforcement requires repo hosting + branch protection (human-gated, HG-3).\n"
    "# Interim enforcement: this file is diff-checked in CI (governance.yml).\n"
    "# S0 paths require dual senior review incl. Security (Plan §7.2, L13).\n"
)


def generate_content(cfg: dict[str, Any], repo_name: str) -> str:
    """Render the CODEOWNERS text for one repo entry (fail-closed on shape)."""
    if not isinstance(cfg, dict):
        raise ToolError(f"{repo_name}: repo entry must be a mapping")
    groups = cfg.get("owner_groups")
    if not isinstance(groups, dict):
        raise ToolError(f"{repo_name}: owner_groups missing/not a mapping")
    s0 = cfg.get("s0_paths") or []
    s1 = cfg.get("s1_paths") or []
    if not isinstance(s0, list) or not isinstance(s1, list):
        raise ToolError(f"{repo_name}: s0_paths/s1_paths must be lists")

    lines: list[str] = [HEADER.rstrip("\n")]
    seen: set[str] = set()
    for path in s0:
        if path in seen:
            raise ToolError(f"{repo_name}: duplicate S0 path {path!r}")
        seen.add(path)
        lines.append(f"{path} { ' '.join(groups.get('s0') or [])}")
    for path in s1:
        if path in seen:
            raise ToolError(f"{repo_name}: duplicate S1 path {path!r}")
        seen.add(path)
        lines.append(f"{path} { ' '.join(groups.get('s1') or [])}")
    if not seen:
        raise ToolError(f"{repo_name}: no S0/S1 paths configured")
    return "\n".join(lines) + "\n"


def process_repo(meta_root: Path, name: str, entry: dict[str, Any], write: bool) -> tuple[dict[str, Any], list[str]]:
    groups_source = load_yaml(meta_root / S0_PATHS_FILE)
    groups = groups_source.get("owner_groups") or {}
    merged = dict(entry)
    merged["owner_groups"] = groups

    rel = meta_root / entry["path"]
    if not rel.exists():
        raise ToolError(f"{name}: repo path {entry['path']} does not exist")
    target = rel / entry["codeowners_file"]

    expected = generate_content(merged, name)
    actual = target.read_text(encoding="utf-8") if target.exists() else None
    fails: list[str] = []

    if actual is None:
        if write:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8")
            status, note = "written", f"{target} created"
        else:
            fails.append(f"{name}: {target} missing (run: python tools/owners_sync.py --write)")
            status, note = "missing", ""
    elif actual != expected:
        if write:
            target.write_text(expected, encoding="utf-8")
            status, note = "updated", f"{target} regenerated"
        else:
            diff = list(
                difflib.unified_diff(
                    actual.splitlines(),
                    expected.splitlines(),
                    fromfile=f"{name} (committed)",
                    tofile=f"{name} (generated)",
                    lineterm="",
                )
            )
            fails.append(f"{name}: CODEOWNERS drift —\n" + "\n".join(diff[:40]))
            status, note = "drift", ""
    else:
        status, note = "in-sync", f"{target} matches generated content"

    info = {
        "repo": name,
        "file": str(target),
        "s0_paths": merged.get("s0_paths") or [],
        "s1_paths": merged.get("s1_paths") or [],
        "status": status,
        "note": note,
    }
    return info, fails


def run(args: argparse.Namespace) -> int:
    # File-tree operation (no git required): the meta root is --repo, which
    # CI passes as the checkout root. s0-paths.yaml must exist there.
    root = Path(args.repo).resolve()
    source = load_yaml(root / S0_PATHS_FILE)
    if not isinstance(source, dict) or not isinstance(source.get("repos"), dict):
        raise ToolError(f"{S0_PATHS_FILE}: expected top-level 'repos' mapping")

    results: list[dict[str, Any]] = []
    all_fails: list[str] = []
    for name in sorted(source["repos"]):
        info, fails = process_repo(root, name, source["repos"][name], args.write)
        results.append(info)
        all_fails.extend(fails)

    return emit(args.json, {"tool": "owners_sync", "mode": "write" if args.write else "check", "repos": results}, fail_messages=all_fails)


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="owners_sync.py",
        description="Generate/check CODEOWNERS from docs/process/s0-paths.yaml.",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify committed files match (CI mode)")
    mode.add_argument("--write", action="store_true", help="write/refresh generated CODEOWNERS files")
    add_common_flags(parser)
    args = parser.parse_args()
    if args.check == args.write:  # neither or both -> usage error
        parser.error("exactly one of --check / --write is required")
    main_with_usage_guard(lambda: run(args))


if __name__ == "__main__":
    main()
