#!/usr/bin/env python3
"""tools/release_notes.py — per-train release notes with the
consumed-upstream table (P10-T6). The plan's law: announcement links
EVIDENCE, not adjectives — every number in the notes traces to a fetched
row or says UNVERIFIED.

Source of truth: the P3 machinery (build/upstream/fetch.py — the
allowlisted choke point, NO new hosts): chromiumdash release rows LIVE
(cited with URL + fetch date), and the CVE-notes endpoint on the SAME
allowlisted host. If the CVE endpoint does not answer with JSON, the CVE
table rows are emitted as `UNVERIFIED (upstream endpoint did not answer
with data on <date>)` — never invented, never silently dropped.

  --train 152 --out release/notes/train-152.md [--check]
      (re)generate; --check is diff-clean (house pattern).
  --fixture FILE   offline deterministic rows (tests); skips the network
Exit: 0 · 1 drift (--check) · 2 usage. Stdlib + the P3 fetch machinery.
"""
from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "build" / "upstream"))

SUPERLATIVE_NOTE = (
    "Voice law: notes state facts with evidence links. No superlatives — "
    "tools/claims_lint.py fails the build otherwise.")


def fetch_rows(train: int) -> tuple[list[dict], str]:
    """LIVE chromiumdash rows through the P3 choke point. Returns
    (rows, citation)."""
    import fetch  # the P3 allowlisted choke point (NO new hosts)
    src = fetch.GitilesFetchSource()
    rows = src.releases("Stable", "Windows", 5)
    today = datetime.date.today().isoformat()
    cite = (f"chromiumdash fetch_releases (allowlisted host, fetched "
            f"{today})")
    return [r for r in rows if int(r.get("milestone", 0)) == train] or rows, cite


def cve_rows(train: int, citation: str) -> list[str]:
    """CVE notes from the SAME allowlisted host; honest UNVERIFIED when
    the endpoint does not answer with JSON."""
    try:
        import fetch
        url = f"{fetch.CHROMIUMDASH}/fetch_cve_notes?offset=0&milestone={train}"
        raw = fetch.GitilesFetchSource()._cached(url, immutable=False)
        if isinstance(raw, bytes):
            import gzip
            if raw[:2] == b"\x1f\x8b":
                import gzip as gz
                raw = gz.decompress(raw)
            raw = raw.decode("utf-8", "replace")
        data = json.loads(raw)
        out = []
        for row in data[:20]:
            out.append(f"| {row.get('cve_id', '?')} | "
                       f"{str(row.get('title', ''))[:60]} | "
                       f"{row.get('severity', {}).get('severity_name', '?') if isinstance(row.get('severity'), dict) else row.get('severity', '?')} |")
        if out:
            return out
    except Exception:
        pass
    return ["| UNVERIFIED | upstream CVE endpoint did not answer with "
            f"data at fetch time ({citation}); consumed-CVE table lands "
            "with the P3 fastlane run — not asserted |"]


def render(train: int, rows: list[dict], cite: str) -> str:
    lines = [
        f"# Release notes — train {train} (GENERATED by "
        "tools/release_notes.py; --check diff-clean)",
        "",
        SUPERLATIVE_NOTE,
        "",
        f"## Consumed upstream (Chromium) — {cite}",
        "",
        "| upstream version | milestone | fetched evidence |",
        "|---|---|---|",
    ]
    for r in rows[:5]:
        lines.append(
            f"| {r.get('version', '?')} | M{r.get('milestone', '?')} | "
            f"[chromiumdash release row](#{cite}) |")
    lines += [
        "",
        f"## Consumed-upstream CVE table (train {train})",
        "",
        "| CVE | title | severity |",
        "|---|---|---|",
        *cve_rows(train, cite),
        "",
        "## Announcement body (facts only)",
        "",
        f"XR {train} tracks Chromium {rows[0].get('version', '?')} "
        f"(M{rows[0].get('milestone', '?')}) at the pinned rev in DEPS; "
        "the update path verifies manifests independent of TLS "
        "(xr-core/update/, golden vectors: 73 cases byte-parity across "
        "both backends).",
        "",
        "Evidence links, not adjectives: [evidence/P10/evidence.json]"
        "(../../evidence/P10/evidence.json) · [transparency attestation]"
        "(../transparency/attestation-example.json) · [release gate]"
        "(../../tools/release_gate.py).",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(prog="release-notes",
                                 description=__doc__.splitlines()[0])
    ap.add_argument("--train", type=int, required=True)
    ap.add_argument("--out", default=None)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--fixture", default=None,
                    help="offline rows file (tests): {'rows': [...], "
                         "'citation': '...'}")
    a = ap.parse_args()
    if a.fixture:
        doc = json.loads(Path(a.fixture).read_text(encoding="utf-8"))
        rows, cite = doc["rows"], doc["citation"]
    else:
        rows, cite = fetch_rows(a.train)
    rendered = render(a.train, rows, cite)
    out = Path(a.out) if a.out else REPO / "release" / "notes" / \
        f"train-{a.train}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    if a.check:
        if out.read_text(encoding="utf-8") != rendered:
            print(f"FAIL: {out} stale (run tools/release_notes.py "
                  f"--train {a.train})")
            return 1
        print(f"PASS: release-notes diff-clean ({out.name})")
        return 0
    out.write_text(rendered, encoding="utf-8")
    print(f"wrote {out} ({len(rows)} upstream row(s); {cite})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
