#!/usr/bin/env python3
"""tools/vectors_to_md.py — generate docs/contracts/policy.md from vectors (P6).

The truth-table document the Plan names as the P6 artifact: every
§1.11-consumable rule, GENERATED from the golden vectors (never hand-drift),
plus the dial/exceptions/enterprise semantics sections that surround them.
`--check` mode (CI): regenerate and diff against the committed file — any
drift fails the build, so the doc always describes what the code does.

Stdlib only. Exit: 0 ok · 1 drift/error · 2 usage.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

EXIT_PASS, EXIT_FAIL, EXIT_USAGE = 0, 1, 2

VECTORS_DEFAULT = "docs/contracts/vectors/policy-resolver-v1.json"

HEADER = """# Effective Policy — the truth table (generated)

> GENERATED by `tools/vectors_to_md.py` from
> `docs/contracts/vectors/policy-resolver-v1.json` — do not edit by hand.
> Regenerate: `python3 tools/vectors_to_md.py --write`
> CI enforces `--check` (regeneration must be diff-clean).

Contract: `effective-policy-v1` (frozen P5; `FROZEN.yaml`). Resolver:
`xr-core/policy` (C++ core, byte-parity with `xr-core/fakes/policy_resolver.py`
on every vector below). The resolver is TOTAL: unknown/absent input ⇒ the
fully-denying policy; there is no "unset ⇒ allow" state (L3: never guess).

## The dial (Standard / Shield / Fortress)

Exactly three positions (§2.6 — unreadable at five). The tier orders
everything monotonically: higher tier = strictly more restrictive, never
less. Identity attributes compose with the tier: an *ephemeral* identity
always gets in-memory storage; a *fortress* identity always gets the
Fortress partition and a dedicated process, whatever the dial says.

| Field | Standard | Shield | Fortress |
|---|---|---|---|
| block ads/trackers/HTTPS-upgrade | on | on | on |
| cosmetic filtering + scriptlets | off | on | on |
| permissions (geo/cam/mic) | ask | deny | deny |
| notifications | ask | ask | deny |
| third-party egress | allowed | blocked | blocked |
| route | direct | proxy | tor |
| fingerprint | reduce | reduce | strict |
| storage (persistent identity) | identity-scoped | identity-scoped | fortress partition |
| autofill (navigation/permission contexts) | on | on | on |
| vault export | off (always) | off (always) | off (always) |
| site isolation / dedicated process | on / off | on / off | on / on |
| letterbox | off | off | on |

## Deny policy (unknown identity / bad origin / unknown class / malformed)

The deny-default is a VALUE, not an error: all blocking on, all permissions
`kDeny`, egress `kDirect` with third-party blocked, fingerprint `kStrict`,
storage `kEphemeral` + in-memory, no autofill, no export, letterbox on.
The single error arm is `kVersionMismatch` (contract_version ≠ 1),
surfaced deny-safe. Every vector below marked `deny` proves a path to it.

## Exceptions (never "forever" in-flow — §1.5, §11.9)

In-flow exception prompts offer **once / session / 7d only**. `permanent`
lives solely in Settings: a stored `permanent` exception is honored only
with `granted_by: settings` (v2 schema); the store REJECTS
permanent + in_flow. Expiry is evaluated at the resolver's INPUT against a
caller-supplied `now_ms` (purity): `7d` entries are active while
`expires_at > now_ms` (fail-closed at equality), `session` while the
session id matches, `once` while `remaining_uses > 0` (the caller
decrements — the resolver never mutates state).

## Enterprise (T7: a layer, not a second brain)

Managed policy may clamp the tier UP (`trust_floor`) and force fields
(`force_fingerprint`, `force_route`, `force_letterbox`,
`force_block_third_party`) AFTER tier resolution. It is signed-or-ignored:
an unsigned, badly-signed, or unverifiable managed doc is NEVER enforced
(ledger row records it). Enterprise cannot force `export_allowed` true —
the schema's const-false outranks every layer.

## Precedence ladder

1. Enterprise floor/forces (signed layer — highest)
2. Explicit request trust (the ⌥ dial for this context)
3. Active exception (in-flow, expiring)
4. Per-identity site binding (⌥-stored)
5. Per-site default binding
6. `kStandard`

Invalid layer entries are dropped — never widened — with a ledger row per
drop; a malformed core request resolves to the deny policy.

## Golden vectors ({count})
"""

VECTOR_ROW = "| {name} | {req} | {expect} |"


def req_summary(req: dict) -> str:
    ident = req.get("identity")
    idv = ident.get("value") if isinstance(ident, dict) else repr(ident)
    idv = (idv[:15] + "…") if isinstance(idv, str) and len(idv) > 16 else idv
    origin = req.get("origin")
    if isinstance(origin, dict):
        dom = origin.get("registrable_domain", "∅")
        sch = origin.get("scheme", "∅")
        orig = f"{sch}://{dom}"
    else:
        orig = repr(origin)
    trust = req.get("trust_context", "—")
    cls = req.get("request_class", "∅")
    cv = req.get("contract_version", "")
    cv = f", cv={cv}" if cv != "" else ""
    return f"`{idv}` @ {orig}, {trust}, {cls}{cv}"


def expect_summary(exp: dict) -> str:
    if "error" in exp:
        return f"**error:** `{exp['error']}`"
    pol = exp.get("ok", {})
    tier = "?"
    if pol.get("letterbox") is True:
        tier = "Fortress-like"
    elif pol.get("permissions", {}).get("notifications") == "kAsk" and \
            pol.get("permissions", {}).get("camera") == "kDeny":
        tier = "Shield-like"
    elif pol.get("permissions", {}).get("camera") == "kAsk":
        tier = "Standard-like"
    else:
        tier = "deny-shaped"
    is_deny = (pol.get("permissions", {}).get("notifications") == "kDeny"
               and pol.get("cosmetic", {}).get("hide_cosmetic") is True
               and pol.get("fingerprint", {}).get("mode") == "kStrict"
               and pol.get("storage_scope", {}).get("scope") == "kEphemeral")
    label = "**deny**" if is_deny else tier
    scope = pol.get("storage_scope", {}).get("scope", "∅")
    route = pol.get("egress", {}).get("route", "∅")
    return f"{label} (storage {scope}, route {route})"


def generate(vectors_path: Path) -> str:
    data = json.loads(vectors_path.read_text(encoding="utf-8"))
    vectors = data["vectors"]
    out = [HEADER.format(count=len(vectors)),
           "| vector | request | expected |",
           "|---|---|---|"]
    for v in vectors:
        out.append(VECTOR_ROW.format(name=f"`{v['name']}`",
                                     req=req_summary(v["request"]),
                                     expect=expect_summary(v["expected"])))
    out.append("")
    out.append("*End of generated document.*")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(prog="vectors_to_md")
    p.add_argument("--vectors", default=VECTORS_DEFAULT)
    p.add_argument("--out", default="docs/contracts/policy.md")
    p.add_argument("--write", action="store_true", help="(re)write the document")
    p.add_argument("--check", action="store_true", help="CI: fail on drift")
    args = p.parse_args(argv)

    vectors_path = Path(args.vectors)
    if not vectors_path.is_file():
        print(f"error: vectors file not found: {vectors_path}", file=sys.stderr)
        return EXIT_USAGE
    doc = generate(vectors_path)
    out_path = Path(args.out)
    if args.write:
        out_path.write_text(doc, encoding="utf-8")
        print(f"wrote {out_path} ({len(doc)} bytes)")
        return EXIT_PASS
    if args.check:
        if not out_path.is_file():
            print(f"FAIL: {out_path} missing (run --write)", file=sys.stderr)
            return EXIT_FAIL
        committed = out_path.read_text(encoding="utf-8")
        if committed != doc:
            print(f"FAIL: {out_path} is stale — regenerate with --write "
                  f"(docs must describe what the code does)", file=sys.stderr)
            return EXIT_FAIL
        print(f"policy.md: regeneration diff-clean ({len(committed)} bytes)")
        return EXIT_PASS
    sys.stdout.write(doc)
    return EXIT_PASS


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
